import Head from "next/head";
import WorkInProgress from "../../components/WorkInProgress";

function StudentsCornerHome() {
    return (
        <>
            <Head>
                <title>Student's Corner</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <WorkInProgress />
            </div>
        </>
    );
}

export default StudentsCornerHome;
